exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"
  - "src/plugins/share/sprites/**"
  - "wet-boew-dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    width: 1
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
