language: node_js
node_js:
  - '0.10'

env:
  global:
    - secure: "PybWgSynVvImOrdX0PFNt5eSqPDyLthWkAG2GsQ1Uz48WoQ2CWxU0HGvGfguM87T+0r44N/ULqTPc02jcQqLsxZbK7UIF3jVZUi1ugY9YqVzMZzxX4M81/EK/SFTLJ6tEvfH/W4+to/wmRqJzwyafxdkP4QZkrilFEPPleXScMw="


install:
  - scripts/setup

script:
  - grunt && ./scripts/travis_artifacts.sh