language: node_js
node_js:
  - '0.10'

env:
  global:
    - secure: "SZ4w7ZHPhzyA4j22Pmm7ICxyy8ikAEo9cbhxT5VFWX3TlQOPSyLUFSFpCdPHvn3Es/iRYVPDLuJhk2d0xs78JMju7aot3DQJcguHARHBMx1dVgn3ve1Q6c0koOCMLsALYfs4MGhLUjk7ndVRL5ZVSpOMtmYJyNJmnnnshZw/YY0="


install:
  - scripts/setup

script:
  - grunt && ./scripts/travis_artifacts.sh